name: Update api docs
on:
  push:
    branches:
      - docs
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      path:
        description: 'Path to generate'
        required: false

jobs:
  build:
    name: Update api docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2.1.5
      - run: npm install -g npm@7.11.2
        continue-on-error: true
      - uses: actions/checkout@v2
        with:
          path: source
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: yeoman-test-doc
      - run: npm ci
        working-directory: source
      - run: npm config set yeoman-test:doc_path ../yeoman-test-doc/${{ github.event.inputs.path }}
        working-directory: source
      - run: npm run doc
        working-directory: source
      - name: Create commit
        working-directory: yeoman-test-doc
        if: always()
        run: |
          git add .
          git config --local user.email ""
          git config --local user.name "Github Actions"
          git commit -a -m "Update api for ${{github.event.release.name}}" || true
      - name: Create Pull Request
        if: always()
        id: cpr
        uses: peter-evans/create-pull-request@v3.8.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Update api for ${{github.event.release.name}}'
          title: 'Update api for ${{github.event.release.name}}'
          body: |
            Update api docs
          labels: automated pr
          branch: gh-pages-master
          path: yeoman-test-doc
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ env.PULL_REQUEST_NUMBER }}"
          echo "Pull Request Number - ${{ steps.cpr.outputs.pr_number }}"
